name: form-example-new2
on:
 workflow_dispatch:

jobs:
    check-bats-version1:
      runs-on: windows-latest
      
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - run: |
             echo "checkout"
             
      #コンポの値設定
        - name: step2
          id: step2
          run: |
             $targetcompo += "["
             foreach ($l in Get-Content ./unittest_setting.json) {
              if ($l -like "*node_name*") {
                $node_name = $l.Substring(22, ($l.Length-24))
               } elseif ($l -like "*scheduled*") {
                if ($l -like "*true*") {
                  $targetcompo += "`""
                  $targetcompo += $node_name
                  $targetcompo += "`""
                  $targetcompo += ","
                  }
                }
               }
             $targetcompo += "]"
             $targetcompo = $targetcompo -replace '\,]',']'

             echo "targetcompo=$targetcompo"

             python3 -m pip install pyyaml
             pip install ruamel.yaml

             $arr = @(aaa, bbb)
             python3 create_jobs.py $($arr -join ' ')
             #ymlファイル生成
             #python3 create_jobs.py $targetcompo
             
    check-bats-version2:
      needs: [ check-bats-version1 ]
      uses: ./.github/workflows/new_test.yml
      name: call_yml
