name: form-example 
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
    inputs:
      no_approval_required_for_workflow_dispatch:
        description: 'JQ member/On-site staff'
        required: false
        type: boolean
      input_mod:
        description: 'Please enter the SHA-1 or branch name to UnitTest.'
        required: false
      input_compo:
        description: 'Please enter the compo name to UnitTest.'
        required: false
      terms_check:
        description: 'Only check the terms and conditions'
        required: false
        type: boolean
        
  workflow_call:
    inputs:
      input_mod:
        type: string
      input_compo:
        type: string
        
jobs:
    call_check-bats-version1:
      #runs-on: ubuntu-latest
      runs-on: windows-latest
      
      steps:
      #環境を設定する
        - name: step1
          id: step1
          uses: actions/checkout@v4
        - run: |
             $terms_check="false"
             echo "terms_check=$terms_check" | Out-File -Append -FilePath $env:GITHUB_ENV
             
      #コンポの値設定
        - name: compo_check
          run: |
             $input_mod='${{ inputs.input_mod }}'
             $terms_check={{ inputs.terms_check }}
             echo "targetmod=$targetmod"
             echo "terms_check=$terms_check"
        #     targetcompo=${{ inputs.input_compo }}
        #     echo "targetcompo=$targetcompo"
             
    call_check-bats-version2:
      runs-on: ubuntu-latest
      needs: [ call_check-bats-version1 ]
      steps:
      #チェック確認
        - name: step2
          id: step2
          run: |
           echo "input_compo=${{ inputs.input_compo }}"
            if [ ${{ inputs.input_compo }} = 'Lcd' ]; then
             echo "Lcdのためエラー"
             exit 1
           fi
           echo "Lcd以外のためエラーなし"
 
    call_check-bats-version3:
      runs-on: windows-latest
      needs: [ call_check-bats-version1,call_check-bats-version2 ]
      if: ${{ github.event.inputs.terms_check == 'false' }}
      steps:
        #環境を設定する
        - name: step3
          run: |
             echo "check"
             
