name: form-example 
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
    inputs:
      no_approval_required_for_workflow_dispatch:
        description: 'JQ member/On-site staff'
        required: false
        type: boolean
      input_mod:
        description: 'Please enter the SHA-1 or branch name to UnitTest.'
        required: false
      input_compo:
        description: 'Please enter the compo name to UnitTest.'
        required: false
      terms_check:
        description: 'Only check the terms and conditions'
        required: false
        type: boolean
        
  workflow_call:
    inputs:
      no_approval_required_for_workflow_dispatch:
        type: boolean
      input_mod:
        type: string
      input_compo:
        type: string
        
jobs:
    call_check-bats-version1:
      runs-on: ubuntu-latest
      
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - run: |
             echo "checkout"
             $terms_check='false'
             
      #コンポの値設定
        - name: compo_check
          run: |
             targetmod=${{ inputs.input_mod }}
             echo "targetmod=$targetmod"
             targetcompo=${{ inputs.input_compo }}
             echo "targetcompo=$targetcompo"
             
    call_check-bats-version2:
      runs-on: ubuntu-latest
      needs: [ call_check-bats-version1 ]
      if: ${{ github.event.inputs.terms_check == 'false' }}

      steps:
      #チェック確認
        - name: step1
          id: step1
          run: |
            if [ ${{ inputs.input_compo }} = 'Lcd' ]; then
              echo "Lcdのためエラー"
              exit 1
            fi
            echo "Bsmのためエラーなし"
 
    call_check-bats-version3:
      runs-on: windows-latest
      needs: [ call_check-bats-version1,call_check-bats-version2 ]

      steps:
        #環境を設定する
        - name: step1
          run: |
             echo "check"
             
