name: jq UnitTest CI Exec job
on:
  workflow_dispatch:
    inputs:
      no_approval_required_for_workflow_dispatch:
        description: 'JQ member/On-site staff'
        required: true
        type: boolean
  workflow_call:
#jobを定義
jobs:
    checkout_and_clean_repo:
      runs-on: windows-latest
      steps:
      #作業用リポジトリのクリーン
        - name: Clean self-hosted runner
          run: |
           echo "--- Get-Location ---"
           Get-Location
           echo "--- Get-PSDrive -Name C ---"
           Get-PSDrive -Name C
           echo "--- github.workspace=${{ github.workspace }} ---"
           $github_workspace="${{ github.workspace }}"
           echo "--- Get-ChildItem -Force | Format-Table (before Remove-Item) ---"
           Get-ChildItem -Force | Format-Table
           echo "--- Remove-Item -Recurse -Force -Path $github_workspace/* ---"
           Remove-Item -Recurse -Force -Path $github_workspace/*
           Remove-Item -Recurse -Force -Path $github_workspace/.??*
           echo "--- Get-ChildItem -Force (after Remove-Item) ---"
           Get-ChildItem -Force

      #作業用リポジトリへチェックアウト
        - name: checkout work-repo
          uses: actions/checkout@v3

    exec_UnitTest_CI_Lcd:
      needs: [checkout_and_clean_repo]
      uses: ./.github/workflows/jq_UnitTest_CI.yml
      name: exec_UnitTest_CI_Lcd
      with:
        input_mod: "master"
        input_compo: "Lcd"
        input_scheduled: "true"

    exec_UnitTest_CI_Bsm:
      needs: [checkout_and_clean_repo]
      uses: ./.github/workflows/jq_UnitTest_CI.yml
      name: exec_UnitTest_CI_Bsm
      with:
        input_mod: "master"
        input_compo: "Bsm"
        input_scheduled: "true"
