name: form-example-new
on:
 workflow_dispatch:
        
jobs:
    check-bats-version1:
      runs-on: windows-latest
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - run: |
             echo "checkout"
             
    job_node:
      needs: [ check-bats-version1 ]
      uses: ./.github/workflows/test_CI_run.yml
      name: yml_compo
      with:
        input_mod: "master"
        input_compo: "Lcd"
