name: form-example-new
on:
 workflow_dispatch:
 workflow_call:
 
#jobを定義
jobs:

#jobを定義  
  job_node:
    uses: ./.github/workflows/test_CI_run.yml
    name:
    with:
      input_mod: master
      input_compo: input_compo
