name: form-example-new 
on:
 workflow_dispatch:
    inputs:
      input_mod:
        description: 'Please enter the SHA-1 or branch name to UnitTest.'
        required: false

jobs:
    check-bats-version1:
      runs-on: windows-latest
      outputs:
       targetcompoA: ${{ steps.step2.outputs.targetcompoA }}
       targetcompoB: ${{ steps.step2.outputs.targetcompoB }}
      
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - run: |
             echo "checkout"
             
      #コンポの値設定
        - name: step2
          id: step2
          run: |
             $targetcompoA="Lcd"
             $targetcompoB="Lcd"
             echo "targetcompoA=$targetcompoA"
             echo "targetcompoB=$targetcompoB"
             echo "targetcompoA=$targetcompoA" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
             echo "targetcompoB=$targetcompoB" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
             
    check-bats-version2:
      runs-on: ubuntu-latest
      needs: [ check-bats-version1 ]
      
      steps:
      #環境を設定する
        - name: step1
          run: |
             targetcompoA=${{ needs.check-bats-version1.outputs.targetcompoA }}
             echo "targetcompoA=$targetcompoA"

    check-bats-version3:
      runs-on: ubuntu-latest
      needs: [ check-bats-version1 ]
      
      steps:
      #環境を設定する
        - name: step1
          run: |
             targetcompoB=${{ needs.check-bats-version1.outputs.targetcompoB }}
             echo "targetcompoB=$targetcompoB"
