name: form-example-new 
on:
 workflow_dispatch:
    inputs:
      input_mod:
        description: 'Please enter the SHA-1 or branch name to UnitTest.'
        required: false

jobs:
    check-bats-version1:
      runs-on: ubuntu-latest
      
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - name: step2
          run: |
            cat ./.github/workflows/test_CI_run.yml | sh
            
           

