name: form-example-new 
on:
 workflow_dispatch:
    inputs:
      input_mod:
        description: 'Please enter the SHA-1 or branch name to UnitTest.'
        required: false
        
 workflow_call:
    inputs:
      input_mod:
        type: string
        
jobs:
    check-bats-version1:
      runs-on: windows-latest
      outputs:
       targetcompo: ${{ steps.step2.outputs.targetcompo }}
       compo_num: ${{ steps.step2.outputs.targetcompo }}
      
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - run: |
             echo "checkout"
             
      #コンポの値設定
        - name: step2
          id: step2
          run: |
             [string[]]$targetcompo = @()
             foreach ($l in Get-Content ./unittest_setting.json) {
              if ($l -like "*node_name*") {
                $node_name = $l.Substring(22, ($l.Length-24))
               } elseif ($l -like "*scheduled*") {
                if ($l -like "*true*") {
                  $targetcompo += $node_name
                  }
               }
             }
             echo "targetcompo=$targetcompo"
             $compo_num=$targetcompo.Count
             echo "compo_num=$compo_num"
             
        - name: step3
          id: step3
          run: |
             echo "お試し"

