name: form-example-new 
on:
 workflow_dispatch:
    inputs:
      input_mod:
        description: 'Please enter the SHA-1 or branch name to UnitTest.'
        required: false
        
 workflow_call:
    inputs:
      input_mod:
        type: string
        
jobs:
    check-bats-version1:
      runs-on: windows-latest
      #outputs:
      # targetcompoA: ${{ steps.step2.outputs.targetcompoA }}
      # targetcompoB: ${{ steps.step2.outputs.targetcompoB }}
      
      steps:
      #環境を設定する
        - name: step1
          uses: actions/checkout@v4
        - run: |
             echo "checkout"
             
      #コンポの値設定
        - name: step2
          id: step2
          run: |
             $targetcompoA="Lcd"
             echo "targetcompoA=$targetcompoA"
             echo "targetcompoA=$targetcompoA" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
             #echo "targetcompoA=$targetcompoA" >> $GITHUB_ENV

        - name: step3
          id: step3
          run: |
             echo "targetcompoA=${env:targetcompoA}"
             
    #check-bats-version2:
    #  needs: [ check-bats-version1 ]
    #  uses: ./.github/workflows/test_CI_run.yml
    #  name: yml_compoA
    #  with:
    #    input_mod: ${{ needs.check-bats-version1.outputs.targetcompoA }}

    #check-bats-version3:
    #  needs: [ check-bats-version1 ]
    #  uses: ./.github/workflows/test_CI_run.yml
    #  name: yml_compoB
    #  with:
    #    input_mod: ${{ needs.check-bats-version1.outputs.targetcompoB }}
