name: form-example-new
on:
 workflow_dispatch:
 workflow_call:
 
#jobを定義
jobs:

#jobを定義  
  job_node1:
    uses: ./.github/workflows/test_CI_run.yml
    name: yml_compo1
    with:
      input_mod: master
      input_compo: Lcd
  job_node2:
    uses: ./.github/workflows/test_CI_run.yml
    name: yml_compo2
    with:
      input_mod: master
      input_compo: Bsm
