name: form-example

on:
 workflow_dispatch:
  inputs:
   input_node:
    description: 'Input Node Name.'
    required: true
    type: choice
   # default: 'node A'
   # options: ${ fromJson( toString( fromFile('choices.json') ) ).['options']}
    options:
     - ${ fromJson( toString( fromFile('choices.json') ) ).'options[0]'}
     - ${ fromJson( toString( fromFile('choices.json') ) ).'options[1]'}
    
    
jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
