name: form-example 
on:
  workflow_dispatch:
    inputs:
      input_node:
        description: 'Serect Node Name.'
        required: false
      input_mirror:
        description: 'Input mirror SHA1.'
        required: false
      input_1node:
        description: 'Input 1node BASE.'
        required: false

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
