name: form-example

on:
  workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
        #options: |
        #  ${ echo(fromJson(file('choices.json')).options) }
    
jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo echo　$(jq -r '.options' choices.json)
        
        
        

