name: form-example 
on:
  workflow_dispatch:
    inputs:
      input_compo:
        description: 'compo_name'
        required: false
      input_node:
        description: ' node_name'
        required: false

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
