name: form-example 
on:
 workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
      input_mirror:
        description: 'Input mirror SHA1.'
        required: true
      input_1node:
        description: 'Input 1node BASE.'
        required: true
        default: 'main'

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
      #入力値を保持
        - name: Set_InputData
          run: |
           INPUT_NODE=${{ inputs.input_node }}
           INPUT_MIRROR=${{ inputs.input_mirror }}
           INPUT_1NODE_BASE=${{ inputs.input_1node }}
           echo "Input: $INPUT_NODE ,$INPUT_MIRROR ,$INPUT_1NODE_BASE"
       
      #現在の日時の取得
      #2023_0519_14_10_30
        - name: Get current datetime
          env:
           TZ: 'Asia/Tokyo' # タイムゾーン指定
          run: echo "CURRENT_DATETIME=$('%Y_%m_%d_%H_%M_%S')" >> $GITHUB_ENV
        
        - name: Print current datetime
          run: echo ${{ env.CURRENT_DATETIME }}
      
      
      #ブランチの作成
        #- name: Create_NewBranch
          #env:
           #BRANCH_NAME: "test"
          #run: git branch $BRANCH_NAME


