name: form-example 
on:
 workflow_dispatch:
    inputs:
      my_input:
        description: 'Select an option'
        type: string
        required: true
        default: 'a'
        options: ${fromJson(file('choices.json'))}

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
