name: form-example 
on:
    workflow_dispatch:
    inputs:
      text:
        type: string
        required: true
        description: 'Text data'
      optional:
        type: string
        required: false
        description: 'Optional data'
      secret:
        type: string
        required: true
        description: 'Secret data'
      flag:
        type: boolean 
        required: true 
        description: 'Flag data'

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
