name: form-example 
on:
 workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
      input_mirror:
        description: 'Input mirror SHA1.'
        required: true
      input_1node:
        description: 'Input 1node BASE.'
        required: true
        default: 'main'

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - name: Echo input
          run: |
           INPUT_NODE=${{ inputs.input_node }}
           INPUT_MIRROR=${{ inputs.input_mirror }}
           INPUT_1NODE_BASE=${{ inputs.input_1node }}
           echo "Input: $INPUT_NODE ,$INPUT_MIRROR ,$INPUT_1NODE_BASE"

