name: form-example 
on:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select an option'
        required: true
        type: choice
        default: 'Option A'
        options: ${ fromJson( file('./choices.json') ).options }

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
