name: form-example 
on:
  workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
        default: 'node A'
        options: ${fromJson(file('./choices.json')).nodes}
        
jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
