jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read choices from JSON file
        id: read_choices
        run: |
          echo "::set-output name=choices::$(cat choices.json | jq -r '.choices | join("\n")')"
        shell: bash
        
      - name: Show prompt and get user input
        id: user_input
        uses: actions/github-script@v4
        with:
          script: |
            const choices = `${steps.read_choices.outputs.choices}`.split('\n'); 
            const {inputs} = await github.prompt("Select a choice.", choices.map((c) => ({label: c, description: ''})), {required: true});
            return {choice: inputs};
          
      - name: Echo user input
        run: |
          echo "User selected: ${steps.user_input.outputs.choice}"
