name: form-example 
on:
 workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
      input_mirror:
        description: 'Input mirror SHA1.'
        required: true
      input_1node:
        description: 'Input 1node BASE.'
        required: true
        default: 'main'

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
      #入力値を保持
        - name: Set_InputData
          run: |
           INPUT_NODE=${{ inputs.input_node }}
           INPUT_MIRROR=${{ inputs.input_mirror }}
           INPUT_1NODE_BASE=${{ inputs.input_1node }}
           echo "Input: $INPUT_NODE ,$INPUT_MIRROR ,$INPUT_1NODE_BASE"
       
      #現在の日時の取得
        - name: Get current datetime
          env:
           TZ: 'Asia/Tokyo' # タイムゾーン指定
          run: echo "CURRENT_DATETIME=$(date +'%Y_%m%d_%H_%M_%S')" >> $GITHUB_ENV
        
        - name: Print current datetime
          run: echo ${{ env.CURRENT_DATETIME }}
          
      
      #ブランチの作成
        #- name: Create_NewBranch
          #env:
           #BRANCH_NAME: "env.CURRENT_DATETIME"
          #run: git branch $BRANCH_NAME
          
        #- name: Create new branch
          #env:
           #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #run: |
           #git switch -c fix/hoge_${{ env.CURRENT_DATETIME }}
           #git push -u origin fix/hoge_${{ env.CURRENT_DATETIME }}

      #入力情報をtextファイルに追加
        - name: create text
          uses: actions/checkout@v2
        - run: |
           echo "NodeName:${{ inputs.input_node }}" >> data_info.txt
           echo "SHA1:${{ inputs.input_mirror }}" >> data_info.txt
           echo "1NodeBase:${{ inputs.input_1node }}" >> data_info.txt
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add .
           git commit -m "generated"
           git push

