name: form-example

on:
  workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
        options: |
          ${ join(fromJson(toString(fromFile('choices.json'))).options, '\n') }   
    
jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
