name: form-example 
on:
 workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
      input_mirror:
        description: 'Input mirror SHA1.'
        required: true
      input_1node:
        description: 'Input 1node BASE.'
        required: true

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - name: Clean self-hosted runner
          run: echo "$inputs.input_node"
