name: form-example 
on:
    workflow_dispatch:
    no_approval_required:
        description: 'JQ member/On-site staff'
        required: true
        type: boolean
      input_base:
        description: 'If you want to do a baseline analysis, enter the base branch name or SHA1 to QAC analysis.'
        required: false

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
