name: form-example 
on:
 workflow_dispatch:
    inputs:
      my_input:
        description: 'Select an node'
        required: true
        default: 'a'
        type: choice
        options: ${ fromJson(  fromFile('choices.json') ) }

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
