name: form-example

on:
  workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
        options: |
          ${ steps.read-json.outputs.options }
          
jobs:
  read-json:
    runs-on: ubuntu-20.04
    steps:
      - name: Read node options from JSON
        id: read-json
        run: echo "::set-output name=options::$(jq -r '.options | join(\"\n\")' choices.json)"
