name: form-example 
on:
    workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
      age:
        description: 'Age of the person'
        required: true

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
