name: form-example 
on:
 workflow_dispatch:
    inputs:
      input_node:
        description: 'Please enter the node name.'
        required: true
      input_mirror:
        description: 'Please enter the mirror branch name or SHA1.'
        required: true
      input_1node:
        description: 'Please enter the 1node base branch name or SHA1.(If there is no input, it will be "main".)'
        required: false

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
      #入力情報をtextファイルに追加
        - name: create text
          uses: actions/checkout@v2
        - run: |
           echo "NodeName:${{ inputs.input_node }}" >> CI_env_info.txt
           echo "SHA1:${{ inputs.input_mirror }}" >> CI_env_info.txt
           echo "1NodeBase:${{ inputs.input_1node }}" >> CI_env_info.txt
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add .
           git commit -m "generated"
           git push
           
      #現在の日時の取得
        - name: Get current datetime
          env:
           TZ: 'Asia/Tokyo' # タイムゾーン指定
          run: echo "CURRENT_DATETIME=$(date +'%Y_%m%d_%H_%M_%S')" >> $GITHUB_ENV
        
        - name: Print current datetime
          run: echo ${{ env.CURRENT_DATETIME }}
           
      #ブランチの作成
        - name: Create New Branch
          uses: actions/checkout@v2
        - run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
           git checkout -b AUTO/${{ inputs.input_node }}/${{ env.CURRENT_DATETIME }}
           git init
           git push -u origin AUTO/${{ inputs.input_node }}/${{ env.CURRENT_DATETIME }}
        
      
