name: form-example 
on:
 workflow_dispatch:
    inputs:
      my_input:
        description: 'Select an node'
        required: true
        type: choice
        options: ${fromJson(file('choices.json [0].value'))}

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
