name: form-example 
on:
 workflow_dispatch:
    inputs:
      my_input:
        description: 'Select an node'
        required: true
        default: 'a'
        type: choice
        options: ${ fromJson(  fromFile('choice.json') ) }
        
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected option
        run: echo "${ github.event.inputs.option }"

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
        - run: echo "Hello world"
