name: form-example 
on:
 workflow_dispatch:
    inputs:
      input_node:
        description: 'Input Node Name.'
        required: true
      input_mirror:
        description: 'Input mirror SHA1.'
        required: true
      input_1node:
        description: 'Input 1node BASE.'
        required: true

jobs:
    check-bats-version:
      runs-on: ubuntu-20.04
      
      steps:
       #- run: echo ${{github.event.inputs.input_node}} > input.json
       #- run: echo -e "{\n  \"NodeName\":\"${{ inputs.input_node }}\",\n  \"SHA1\":\"${{ inputs.input_mirror }}\"\n}" \
       #     > $config.json
       - run: |
          echo '${\n  \"NodeName\":\"${{ inputs.input_node }}\",\n  \"SHA1\":\"${{ inputs.input_mirror }}\"\n}' \
            > $setting.txt
          chmod +x results
          mv setting.txt ./results
          echo "File contents: "
          cat results/setting.txt 
          # アーティファクトをアップロードする
          uses: actions/upload-artifact@v2
          with:
          name: setting
          path: results/
